title = "Edouard Paris"
baseURL = "https://edouard.paris"
theme = "phrck"
DefaultContentLanguage = "en"

[blackfriday]
angledQuotes = false

[languages]
[languages.en]
copyright= "my copyright"

[languages.fr]
copyright= ""

[languages.fr.blackfriday]
angledQuotes = true
