title = "Edouard Paris"
baseURL = "https://edouard.paris"
theme = "phrck"
DefaultContentLanguage = "en"

[blackfriday]
angledQuotes = false

[languages.en]
copyright = "my copyright"

[[languages.en.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre= "/"

[[languages.en.menu.lang]]
url = "/"
name = "en"
weight = 0

[[languages.en.menu.main]]
url = "/contact"
name = "contact"
weight = 0

[[languages.en.menu.main]]
url = "/reading"
name = "reading"
weight = 0

[languages.fr]
copyright= ""

[[languages.fr.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre = "/"

[[languages.fr.menu.lang]]
url = "/"
name = "en"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/contact"
name = "contact"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/lecture"
name = "lecture"
weight = 0

[[languages.fr.blackfriday]]
angledQuotes = true
