title = "edouard.paris"
baseURL = "https://edouard.paris"
theme = ["phrck", "reveal-hugo"]
DefaultContentLanguage = "en"
pluralizeListTitles = false

[blackfriday]
angledQuotes = false

[outputFormats]
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[outputFormats.Txt]
name = "txt"
baseName = "index"
mediaType = "text/plain"
isPlainText = true

[outputs]
 home = ["HTML", "txt"]
 page = ["HTML", "txt"]
 section = ["HTML", "txt"]

[languages.en]
copyright = "2018 EdouardParis."

[[languages.en.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre= "/"

[[languages.en.menu.lang]]
url = "/"
name = "en"
weight = 0


[[languages.en.menu.main]]
url = "/reading"
name = "reading"
identifier = "reading"
weight = 1

[[languages.en.menu.main]]
url = "/reading/books"
name = "books"
parent = "reading"
weight = 0

[[languages.en.menu.main]]
name = "writing"
identifier = "writing"
weight = 2

[[languages.en.menu.main]]
url = "https://github.com/edouardparis"
name = "code"
parent = "writing"
weight = 0

[[languages.en.menu.main]]
name = "speaking"
identifier = "speaking"
weight = 3

[[languages.en.menu.main]]
url = "/talks"
name = "talks"
parent = "speaking"
weight = 0

[[languages.en.menu.main]]
name = "about"
identifier = "about"
weight = 0


[[languages.en.menu.main]]
url = "/contact"
name = "contact"
parent = "about"
weight = 0

[[languages.en.menu.main]]
url = "https://tippin.me/@edouardparis"
name = "tip ⚡ "
parent = "about"
weight = 0

[languages.fr]
copyright = "2018 EdouardParis."

[[languages.fr.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre = "/"

[[languages.fr.menu.lang]]
url = "/"
name = "en"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/reading"
name = "lecture"
identifier = "lecture"
weight = 1

[[languages.fr.menu.main]]
url = "/fr/reading/books"
name = "livres"
parent = "lecture"
weight = 0

[[languages.fr.menu.main]]
name = "écrits"
identifier = "écrits"
weight = 2

[[languages.fr.menu.main]]
url = "https://github.com/edouardparis"
name = "code"
parent = "écrits"
weight = 0

[[languages.fr.menu.main]]
name = "à propos"
identifier = "a-propos"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/contact"
name = "contact"
parent = "a-propos"
weight = 0

[[languages.fr.menu.main]]
url = "https://tippin.me/@edouardparis"
name = "tip ⚡ "
parent = "a-propos"
weight = 0


[[languages.fr.blackfriday]]
angledQuotes = true
