title = "edouard.paris"
baseURL = "https://edouard.paris"
theme = ["phrck"]
DefaultContentLanguage = "en"
pluralizeListTitles = false
enableGitInfo = true

[markup]
[markup.tableOfContents]
endLevel = 3
startLevel = 1
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'lovelace'
tabWidth = 4

[taxonomies]
tag = "tags"
topic = "topics"

[permalinks]
topics = "/:slug"

[frontmatter]
date = ["date", "lastmod"]
lastmod = [":git"]

[outputFormats.Txt]
name = "txt"
baseName = "index"
mediaType = "text/plain"
isPlainText = true

[outputs]
home = ["HTML", "txt"]
page = ["HTML", "txt"]
section = ["HTML", "txt", "RSS"]

[languages]
[languages.en]
[languages.en.params]
redirect = "Read this page in your terminal with the command:"
copyright = "2024 EdouardParis."
description = "Edouard Paris personal website"
[[languages.en.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre= "/"
[[languages.en.menu.lang]]
url = "/"
name = "en"
weight = 0
[[languages.en.menu.main]]
url = "/readings"
name = "readings"
weight = 0
[[languages.en.menu.main]]
name = "writing"
identifier = "writing"
weight = 2
[languages.fr]
[languages.fr.params]
redirect = "Lisez cette page dans un terminal avec la commande:"
copyright = "2024 EdouardParis."
description = "Site web personnel de Edouard Paris"
[[languages.fr.params.blackfriday]]
angledQuotes = true
[[languages.fr.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre = "/"
[[languages.fr.menu.lang]]
url = "/"
name = "en"
weight = 0
[[languages.fr.menu.main]]
url = "/fr/lecture"
name = "lecture"
weight = 0
